//export const baseUrl = 'http://192.168.188.123:8081/O.OBusinessPlan'
// const baseUrl = 'http://39.97.99.250:8080/O.OBusinessPlan'
// export const baseUrl = 'http://192.168.3.25:8081/O.OBusinessPlan'
//export const baseUrl = 'http://localhost:8081/O.OBusinessPlan'
export const baseUrl = 'http://www.caiyangzhi.com/appServer'
export const adminUrl = baseUrl + '/api/admin'
export const employeeUrl = baseUrl + '/api/employee'
export const roleUrl = baseUrl + '/api/authority/roles'
export const resouUrl = baseUrl + '/api/authority/resource'
export const authUrl = baseUrl + '/api/authority/auth'
export const classifyUrl = baseUrl + '/api/article/classify'
export const diaryUrl = baseUrl + '/api/article/diary'
export const labelUrl = baseUrl + '/api/article/label'
export const reportUrl = baseUrl + '/api/article/finalresport'
export const novelUrl = baseUrl + '/api/article/novel'

export const loginUrl = 'http://localhost:8082/oobusinessplan/#/login'
// const loginUrl = 'http://localhost:8080/oobusinessplan/#/login'

export const fileUrl = 'http://www.caiyangzhi.com/OOBusinessPlanFile'